modLoader="lowcodefml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/elucent/GravelOres/issues"
license="MIT"
[[mods]]
    modId="gravelores"
    version="2.2.1"
    displayName="Gravel Ores"
    logoFile="pack.png"
    authors="elucent, KnightMiner"
    description='''
    Adds gravel versions of vanilla and various modded ores that spawn in your world, as a means of gathering such resources without long mining trips
    '''
    displayURL="https://slimeknights.github.io/projects/#simple-gravel-ores"
[[dependencies.gravelores]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.21.11]"
    ordering="NONE"
    side="BOTH"
[[dependencies.gravelores]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gravelores]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.13.4,)"
    ordering="NONE"
    side="BOTH"
